import numpy as np
import matplotlib.pyplot as plt

r50_1 = np.load('avg_rets_1.npy')
r50_2 = np.load('avg_rets_2.npy')
r50_3 = np.load('avg_rets_3.npy')
r50_nb1 = np.load('avg_rets_nb_1.npy')
r50_nb2 = np.load('avg_rets_nb_2.npy')
r50_nb3 = np.load('avg_rets_nb_3.npy')
r200_1 = np.load('avg_rets_200_1.npy')
r200_2 = np.load('avg_rets_200_2.npy')
r200_3 = np.load('avg_rets_200_3.npy')
r200_nb1 = np.load('avg_rets_nb_200_1.npy')
r200_nb2 = np.load('avg_rets_nb_200_2.npy')
r200_nb3 = np.load('avg_rets_nb_200_3.npy')

#piles
x = np.arange(1, 51)
plt.plot(x, r50_1, label='b1', color='red')
plt.plot(x, r50_2, label='b2', color='orange')
plt.plot(x, r50_3, label='b3', color='yellow')
plt.plot(x, r50_nb1, label='nb1', color='blue')
plt.plot(x, r50_nb2, label='nb2', color='black')
plt.plot(x, r50_nb3, label='nb3', color='green')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()
#with baseline
plt.plot(x, r50_1, label='b1', color='red')
plt.plot(x, r50_2, label='b2', color='orange')
plt.plot(x, r50_3, label='b3', color='yellow')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()
#without baseline
plt.plot(x, r50_nb1, label='nb1', color='blue')
plt.plot(x, r50_nb2, label='nb2', color='black')
plt.plot(x, r50_nb3, label='nb3', color='green')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()
#200 piles
x = np.arange(1, 201)
plt.plot(x, r200_1, label='b1', color='red')
plt.plot(x, r200_2, label='b2', color='orange')
plt.plot(x, r200_3, label='b3', color='yellow')
plt.plot(x, r200_nb1, label='nb1', color='blue')
plt.plot(x, r200_nb2, label='nb2', color='black')
plt.plot(x, r200_nb3, label='nb3', color='green')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()
#200 with baseline
plt.plot(x, r200_1, label='b1', color='red')
plt.plot(x, r200_2, label='b2', color='orange')
plt.plot(x, r200_3, label='b3', color='yellow')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()
#200 without baseline
plt.plot(x, r200_nb1, label='nb1', color='blue')
plt.plot(x, r200_nb2, label='nb2', color='black')
plt.plot(x, r200_nb3, label='nb3', color='green')
plt.xlabel('iterations')
plt.ylabel('average_returns')
plt.ylim(0, 210)
plt.show()

